MONGODB_URI = "mongodb://localhost:27017/"
DB_NAME = "shopee_db"
COLLECTION_NAME = "products"
LICENSE_SERVER = "https://license-checker.horahora04.workers.dev"
SECRET_KEY = "super_secret_key_123"
